### PR TITLE
Updated to the latest endpoints

### PR DESCRIPTION
**Pull request by Chosey98**
Hastebin got acquired by toptal

### CODE REVIEW

**Review by Fabio1988 — CHANGES_REQUESTED** [review]
new API endpoints should be used.. hmm it seems that both are not working correctly...

https://hastebin.com/about.md

**Comment by Chosey98** [comment]
@Fabio1988 Fixed <3

**Comment by Chosey98** [comment]
Tested as well so you can go ahead and merge

**Comment by Fabio1988** [comment]
> @Fabio1988 Fixed <3

There are no changes ;)
I am no maintainer, but I am also interested in a fix.. but several endpoints are returning html response, useless :(

**Comment by Chosey98** [comment]
Oh if these are the old endpoints then they reverted back to them so you can go ahead and close this pr which means it got fixed directly by them😅 Because I just tested out my changes and they were working fine so .. yeah😅

**Pull request closed without merging**
